docs: clarify plugins don't update devtools timeline
posva/pinia pull request #1002
Opened 2022-01-27 16:53 UTC by Matt-Deacalion

Related to issue: #996

2022-01-27 17:41 UTC, Matt-Deacalion commented
Apologies for the force pushes; no more.

I had issues getting Vitepress to work - I changed [this line](https://github.com/vuejs/pinia/blob/v2/packages/docs/vite.config.ts#L37) to "_../pinia/dist/pinia.esm-**browser**.js_" and it worked fine.

2022-01-27 17:42 UTC, Matt-Deacalion commented
Ugh, one more force push. One minute.

2022-01-31 13:13 UTC, posva requested changes

2022-01-31 13:13 UTC, posva commented on packages/docs/core-concepts/plugins.md
> +State changes that occur within a plugin are not recorded in the devtools timeline.
let's move it above the warning and remove the :::info.

2022-01-31 19:48 UTC, posva commented on packages/docs/core-concepts/plugins.md
> +State changes that occur within a plugin are not recorded in the devtools timeline.
```suggestion
Note that state changes or additions that occur within a plugin (that includes calling `store.$patch()`) happen before the store is active and therefore **do not trigger any subscriptions**.
```

2022-01-31 19:48 UTC, merged