docs: add hint on destructuring actions from store
posva/pinia pull request #1040
Opened 2022-02-09 07:41 UTC by taist24

Added a warning section to hint the user on how to destructure `actions` from the `store`.

2022-02-09 08:21 UTC, posva requested changes
Let's add more code to the example above with an `increment` action and a comment above it

2022-02-09 10:04 UTC, posva requested changes
I meant adding an example at https://github.com/vuejs/pinia/pull/1040/files#diff-8a9cb33bb1a330b9122d09d866b65789f9b8e62d1c02abaeb79ee9a1fb5a249cR77 instead of the warning you added, just add a new line showing how to extract the increment action and add a comment above it.

2022-02-09 10:21 UTC, taist24 commented
Alright, and do you suggest keeping the "tip" section at the bottom? or removing it?

2022-02-09 10:25 UTC, posva commented
remove the whole warning

2022-02-15 18:14 UTC, taist24 commented
Hey, were you able to review the last changes?  I've removed the warning layout and instead added it as an example.

2022-02-18 23:04 UTC, closed without merging

2022-02-18 23:04 UTC, posva commented
Thanks, I did a few changes but couldn't push to your branch likely because you didn't check the "allow maintainers to edit"