docs(zh): add new zh docs
posva/pinia pull request #1193
Opened 2022-04-02 09:34 UTC by KimYangOfCat

2022-04-11 14:11 UTC, KimYangOfCat commented
Hi, everyone, I am so happy to tell you that I have finished the chinese docs translation. If you are good to Chinese , I am willing to get your suggestion of review.
Now, you can click [here](https://deploy-preview-1193--pinia-official.netlify.app/) to preview.

2022-06-08 07:32 UTC, ChpShy commented
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/25942328/172558457-b016f5f9-eced-49b8-ae0c-e0e586bc8139.png">
这里翻译成【商店】？我觉得应该是直接用store吧？

2022-06-08 07:34 UTC, murongg commented
> <img alt="image" width="1253" src="https://user-images.githubusercontent.com/25942328/172558457-b016f5f9-eced-49b8-ae0c-e0e586bc8139.png">
> 
> 这里翻译成【商店】？我觉得应该是直接用store吧？

这个可能是作者机器翻译的😄

2022-06-08 07:39 UTC, ChpShy commented
> > <img alt="image" width="1253" src="https://user-images.githubusercontent.com/25942328/172558457-b016f5f9-eced-49b8-ae0c-e0e586bc8139.png">
> > 这里翻译成【商店】？我觉得应该是直接用store吧？
> 
> 这个可能是作者机器翻译的😄

估计是的。可能遗漏了吧😄

2022-06-08 07:40 UTC, ChpShy commented
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/25942328/172559732-560fbe60-28ee-473b-9572-c58037bca0aa.png">

2022-06-08 13:58 UTC, KimYangOfCat commented
> 这个可能是作者机器翻译的😄

翻译过程中有部分借助机翻，但都经过一次人工校对，这里应该是我疏忽了，多谢指出，我立马修改。

下次提意见的时候，如果可以的话，请按标准的 review 方式操作吧。这样可以加快 BUG 修改，你也可以成为本 PR 的贡献者，目前这样的截图方式并不是很方便

2022-06-08 14:40 UTC, PatrickChen928 commented
> > 这个可能是作者机器翻译的😄
> 
> 为了提升速度，翻译过程中确实有部分借助机翻，但都经过一次人工校对，这里应该是我疏忽了，多谢指出，我立马修改。
> 
> 下次提意见的时候，如果可以的话，请按[标准的 review 方式](https://docs.github.com/cn/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request)操作吧。这样可以加快 BUG 修改，你也可以成为本 PR 的贡献者，当本 PR 被 merge 之后你也可以成为仓库贡献者。目前这样的截图方式并不是很方便。

ok. 我的疏忽。大致翻了下看到的问题，就直接评论了。下次我注意～

2022-06-11 05:50 UTC, ChpShy approved these changes

2022-06-22 08:01 UTC, Aimer-Fan requested changes
翻译遗漏和格式错误

2022-06-22 08:01 UTC, aimer-fan commented on packages/docs/zh/cookbook/testing.md
> +Since the store is named _"counter"_, you need to add a matching object to `initialState`:
由于store的名字叫counter，所以你需要传递相应的对象给`initialState`:

2022-06-22 08:01 UTC, aimer-fan commented on packages/docs/zh/cookbook/testing.md
> +你可以在[测试包的测试]（https://github.com/vuejs/pinia/blob/v2/packages/testing/src/testing.spec.ts）中找到更多的例子。
你可以在[测试包的测试](https://github.com/vuejs/pinia/blob/v2/packages/testing/src/testing.spec.ts)中找到更多的例子。

2022-06-22 08:01 UTC, aimer-fan commented on packages/docs/zh/cookbook/composing-stores.md
> +The same applies to _actions_:
同样适用于_actions_:

2022-06-23 04:46 UTC, KimYangOfCat commented
@Aimer-Fan  Thanks for your review, I have fixed them. If no other suggestions, please approve this PR, thanks again!

2022-06-23 05:41 UTC, Aimer-Fan approved these changes

2022-06-30 18:29 UTC, arnonrdp approved these changes
This is a big step towards opening up more languages to documentation.

Please merge as soon as possible.

2022-07-16 07:15 UTC, KimYangOfCat commented
@posva  there are more than two people that has approved this PR , so can it be merged as soon as possible?

2022-08-20 03:20 UTC, awxiaoxian2020 requested changes

2022-08-20 03:20 UTC, awxiaoxian2020 commented on packages/docs/zh/introduction.md
> +Pinia [最初](https://github.com/vuejs/pinia/commit/06aeef54e2cad66696063c62829dac74e15fd19e)是在 2019 年 11 月左右作为一个使用 [Composition API](https://github.com/vuejs/composition-api) 的实验进行设计的。从那时起，同时支持 Vue2 和
```suggestion
Pinia [最初](https://github.com/vuejs/pinia/commit/06aeef54e2cad66696063c62829dac74e15fd19e)是在 2019 年 11 月左右作为一个使用 [组合式 API](https://github.com/vuejs/composition-api) 的实验进行设计的。从那时起，同时支持 Vue2 和 Vue3 以及不强制要求使用组合式 API 的初始原则保留至今。除了**安装**和**SSR**之外，支持 Vue3 和 Vue2 的 API 都是相同的。虽然这些文档主要是面向 Vue3，但在必要时会标注出 Vue2 的内容，因此 Vue2 和 Vue3 的用户都可以阅读本文档。
```
建议参照 Vue 官方文档翻译成对应中文。

2022-08-20 03:20 UTC, awxiaoxian2020 commented on packages/docs/zh/introduction.md
> +Pinia 是专属 Vue 的 store 库，它允许你跨组件/页面共享状态。如果你熟悉 Composition API 的话，你可能会认为你可以通过一行简单的 `export const state = reactive({})`来共享一个全局状态。对于单页应用程序来说确实是这样的，但如果在服务器端渲染，这可能会使您的应用程序暴露出一些安全漏洞。 不过若是使用 Pinia，即使在小型单页应用程
```suggestion
Pinia 是专属 Vue 的状态管理库，它允许你跨组件/页面共享状态。如果你熟悉组合式 API 的话，你可能会认为你可以通过一行简单的 `export const state = reactive({})`来共享一个全局状态。对于单页应用程序来说确实是这样的，但如果在服务器端渲染，这可能会使您的应用程序暴露出一些安全漏洞。 不过若是使用 Pinia，即使在小型单页应用程序中，你也可以获得很多好处：
```
同上。

2022-08-20 03:45 UTC, awxiaoxian2020 requested changes

2022-08-20 03:45 UTC, awxiaoxian2020 commented on packages/docs/zh/introduction.md
> +Pinia (发音为 `/piːnjʌ/`，类似英文中的 “peenya”) 是最接近有效包名 piña（西班牙语中的 _pineapple_）的词。 菠萝实际上是一组各自独立的花朵，它们结合在一起，由此形成一个多重的水果。 与 Store 类似，每一个都是独立诞生的，但最终它们都是相互联系的。 它也是一种原产于南美洲的美味热带水果。
```suggestion
Pinia (发音为 `/piːnjʌ/`，类似英文中的 “peenya”) 是最接近有效包名 piña（西班牙语中的 _pineapple_，即“菠萝”）的词。 菠萝花实际上是一组各自独立的花朵，它们结合在一起，由此形成一个多重的水果。 与 Store 类似，每一个都是独立诞生的，但最终它们都是相互联系的。 它（菠萝）也是一种原产于南美洲的美味热带水果。
```

2022-08-20 03:45 UTC, awxiaoxian2020 commented on packages/docs/zh/introduction.md
> +最初，Pinia 没有经过任何 RFC。我根据自己开发应用程序的经验，同时阅读其他人的代码，为使用 Pinia 的客户工作，以及在 Discord 上回答问题，测试了一些想法。
```suggestion
最初，Pinia 没有经过任何 RFC 的流程。我根据自己开发应用程序的经验，同时阅读其他人的代码，为使用 Pinia 的客户工作，以及在 Discord 上回答问题，验证了一些想法。
```

2022-08-20 03:45 UTC, awxiaoxian2020 commented on packages/docs/zh/introduction.md
> +现在 Pinea 已经成为默认的状态管理解决方案，它和 Vue 生态系统中的其他核心库一样，都要经过 RFC 流程，其 API 已经进入稳定状态。
```suggestion
现在 Pinia 已经成为默认的状态管理解决方案，它和 Vue 生态系统中的其他核心库一样，都要经过 RFC 流程，其 API 已经变得稳定。
```

2022-08-20 03:45 UTC, awxiaoxian2020 commented on packages/docs/zh/introduction.md
> +- _mutation_ 不再存在。它们经常被认为是**极其冗长的**。它们最初带来了 devtools 的集成，但这已不再是一个问题了。
```suggestion
- _mutation_ 不再存在。它们经常被认为是**极其冗长的**。它们最初带来了 devtools 的集成方案，但这已不再是一个问题了。
```

2022-08-20 03:53 UTC, awxiaoxian2020 requested changes

2022-08-20 03:53 UTC, awxiaoxian2020 commented on packages/docs/zh/getting-started.md
> +并非所有的应用程序都需要访问全局状态，但如果你的应用程序需要一个全局状态，Pinia 将使你的生活更轻松。
```suggestion
并非所有的应用程序都需要访问全局状态，但如果你的应用程序需要一个全局状态，Pinia 将使你的开发更轻松。
```
感觉英文使用 life 没有问题，但是中文使用“生活”就有点奇怪。

2022-08-20 03:53 UTC, awxiaoxian2020 commented on packages/docs/zh/ssr/index.md
> +如果你使用的是 **Nuxt.js，**你需要阅读的是[**这些说明文档**](./nuxt.md)。
```suggestion
如果你使用的是 **Nuxt.js**，你需要阅读的是[**这些说明文档**](./nuxt.md)。
```

2022-08-21 00:40 UTC, awxiaoxian2020 commented
@KimYangOfCat Could you please check other Composition API translation, and replace the `Store` to "状态管理" when neccessary ( e.g. in index title description) if you have spare time?

2022-08-21 07:26 UTC, KimYangOfCat commented
> @KimYangOfCat Could you please check other Composition API translation, and replace the `Store` to "状态管理" when neccessary ( e.g. in index title description) if you have spare time?

@awxiaoxian2020  thanks for your reminder. this PR has some conflicts due to update now. I will update my branch and translate new content recently, and previous tanslations will be checked.

2022-08-25 11:48 UTC, awxiaoxian2020 commented
And the CI seems failed. Do we need to fix it?

2022-08-25 14:05 UTC, KimYangOfCat commented
yes, but now there's no rush, I need to finish translating the update first.

2022-09-30 03:28 UTC, awxiaoxian2020 requested changes

2022-09-30 03:28 UTC, awxiaoxian2020 commented on packages/docs/zh/introduction.md
> +Pinia [起始](https://github.com/vuejs/pinia/commit/06aeef54e2cad66696063c62829dac74e15fd19e)于 2019 年 11 月左右的一场实验，该实验的目的是设计一个拥有 [组合式 API](https://github.com/vuejs/composition-api) 的 Store。从那时起，同时支持 Vue2
```suggestion
Pinia [起始](https://github.com/vuejs/pinia/commit/06aeef54e2cad66696063c62829dac74e15fd19e)于 2019 年 11 月左右的一次实验，该实验的目的是设计一个拥有 [组合式 API](https://github.com/vuejs/composition-api) 的 Vue 状态管理库。从那时起，我们就倾向于同时支持 Vue2 和 Vue3，并且不强制要求使用组合式 API，我们的初心至今没有改变。除了**安装**和 **SSR** 等章节之外，其余章节内容的 API 均支持 Vue3 和 Vue2。虽然本文档主要是面向 Vue3 的用户，但在必要时会标注出 Vue2 的内容，因此 Vue2 和 Vue3 的用户都可以阅读本文档。
```

2022-09-30 03:28 UTC, awxiaoxian2020 commented on packages/docs/zh/introduction.md
> +## 基础示例{#basic-example}
```suggestion
## 基础示例 {#basic-example}
```

2022-09-30 03:28 UTC, awxiaoxian2020 commented on packages/docs/zh/introduction.md
> +## 更真实的示例{#a-more-realistic-example}
```suggestion
## 更真实的示例 {#a-more-realistic-example}
```

2022-09-30 03:28 UTC, awxiaoxian2020 commented on packages/docs/zh/introduction.md
> +这是一个更完整的你将会使用的 Pinia API 示例，即使在 JavaScript 中也具有类型提示。对于某些人来说，可能足以在不进一步阅读的情况下直接开始阅读本节内容，但我们仍然建议你继续阅读文档的其余部分，甚至跳过此示例，在阅读完所有**核心概念**之后再返回。
```suggestion
这是一个更完整的 Pinia API 示例，在 JavaScript 中也使用了类型提示。对于某些人来说，可能足以在不进一步阅读的情况下直接开始阅读本节内容，但我们仍然建议你继续阅读文档的其余部分，甚至跳过此示例，在阅读完所有**核心概念**之后再回来。
```

2022-09-30 03:28 UTC, awxiaoxian2020 commented on packages/docs/zh/introduction.md
> +最初，Pinia 没有经过任何 RFC 的流程。我基于自己开发应用程序的经验，同时通过阅读其他人的代码，为使用 Pinia 的客户工作，以及在 Discord 上回答问题等方式验证了一些想法。
```suggestion
最初，Pinia 没有经过任何 RFC 的流程。我基于自己开发应用程序的经验，同时通过阅读其他人的代码，为使用 Pinia 的用户工作，以及在 Discord 上回答问题等方式验证了一些想法。
```

2022-09-30 03:28 UTC, awxiaoxian2020 commented on packages/docs/zh/introduction.md
> +这些使我能够产出了这样一个可行的解决方案，并适应各种情况和应用规模。我一直在保持其核心 API 不变的情况下发布新版本同时不断优化本库。
```suggestion
这些使我产出了这样一个可行的解决方案，并适应各种场景和应用规模。我一直在保持其核心 API 不变的情况下发布新版本，同时不断优化本库。
```

2022-09-30 03:28 UTC, awxiaoxian2020 commented on packages/docs/zh/ssr/index.md
> +只要你在 `setup` 函数、`getters` 和 `actions` 的顶部调用 `useStore()` 函数，使用 Pinia 创建 store 对于 SSR 来说应该是开箱即用。
```suggestion
只要你在 `setup` 函数、`getters` 和 `actions` 的顶部调用 `useStore()` 函数，使用 Pinia 创建 store 对于 SSR 来说应该是开箱即用的。
```

2022-09-30 03:28 UTC, awxiaoxian2020 commented on packages/docs/zh/introduction.md
> +Pinia 是 Vue 的专属状态管理库，它允许你跨组件/页面共享状态。如果你熟悉组合式 API 的话，你可能会认为你可以通过一行简单的 `export const state = reactive({})`来共享一个全局状态。对于单页应用程序来说确实是这样的，但如果在服务器端渲染，这可能会使您的应用程序暴露出一些安全漏洞。 若是使用 Pinia，即使在小型单页应用程序中，你也可以获得如下功能：
```suggestion
Pinia 是 Vue 的专属状态管理库，它允许你跨组件/页面共享状态。如果你熟悉组合式 API 的话，你可能会认为你可以通过一行简单的 `export const state = reactive({})`来共享一个全局状态。对于单页应用程序来说确实是这样的，但如果在服务器端渲染，这可能会使您的应用程序暴露出一些安全漏洞。 如果使用 Pinia，即使在小型单页应用程序中，你也可以获得如下功能：
```

2022-09-30 03:28 UTC, awxiaoxian2020 commented on packages/docs/zh/introduction.md
> +Pinia 起源于一场探索 Vuex 下一个迭代的实验，所以其结合了 Vuex 5 核心团队讨论中的许多想法。最终，我们意识到 Pinia 已经实现了我们在 Vuex 5 中想要的大部分功能，所以决定将其作为新的推荐方案来代替 Vuex。
```suggestion
Pinia 起源于一次探索 Vuex 下一个迭代的实验，所以其结合了 Vuex 5 核心团队讨论中的许多想法。最终，我们意识到 Pinia 已经实现了我们在 Vuex 5 中想要的大部分功能，所以决定将其作为新的推荐方案来代替 Vuex。
```

2022-09-30 03:28 UTC, awxiaoxian2020 commented on packages/docs/zh/introduction.md
> +- 不再有嵌套结构的**模块**。你仍然可以通过导入和使用另一个 Store 来隐含地嵌套 stores 空间，虽然是 Pinia 从设计上提供的是一个扁平的结构，但仍然能够在 Store 之间进行交叉组合。**你甚至可以让 Stores 有循环依赖关系**。
英文单词是否一律使用单数较为合适？

2022-09-30 14:26 UTC, KimYangOfCat commented on packages/docs/zh/introduction.md
> +- 不再有嵌套结构的**模块**。你仍然可以通过导入和使用另一个 Store 来隐含地嵌套 stores 空间，虽然是 Pinia 从设计上提供的是一个扁平的结构，但仍然能够在 Store 之间进行交叉组合。**你甚至可以让 Stores 有循环依赖关系**。
这个问题，我并不确定，还是得具体问题具体分析吧，不过后续会参考 [Vue 中文文档翻译须知](https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5)中的一些适用要求，统一调整一些格式问题。感谢你的校对，多谢！

2022-10-14 04:20 UTC, awxiaoxian2020 requested changes

2022-10-14 04:20 UTC, awxiaoxian2020 commented on packages/docs/zh/api/modules/pinia_nuxt.md
> +## 接口{#interfaces}
```suggestion
## 接口 {#interfaces}
```

2022-10-14 04:20 UTC, awxiaoxian2020 commented on packages/docs/zh/api/modules/pinia_nuxt.md
> +### 默认值{#default}
```suggestion
### 默认值 {#default}
```

2022-10-14 04:20 UTC, awxiaoxian2020 commented on packages/docs/zh/api/modules/pinia_nuxt.md
> +#### 参数{#parameters}
```suggestion
#### 参数 {#parameters}
```

2022-10-14 04:20 UTC, awxiaoxian2020 commented on packages/docs/zh/api/modules/pinia_nuxt.md
> +#### 返回值{#returns}
```suggestion
#### 返回值 {#returns}
```

2022-10-17 04:18 UTC, awxiaoxian2020 approved these changes
LGTM.

I think it should be merged first and improve later.

2022-10-17 05:01 UTC, KimYangOfCat commented
> I think it should be merged first and improve later.
@awxiaoxian2020  Agree!
@posva  PTAL

2022-10-17 06:23 UTC, posva commented
Thanks a lot for this @KimYangOfCat 
I'm still waiting for vitepress to support i18n in their newer versions, that way, the font will also be changed. Hopefull this change should be really close

2022-10-17 11:12 UTC, KimYangOfCat commented
@posva 
I've looked at the progress of vitepress i18n and it's only about 50%, so there may be some time before it's actually released. Perhaps you could consider merging this PR first, and then I would upgrade the dependencies and modify the configuration once vitepress i18n is officially released. I believe this would not cause any more work, and it would be a good transition solution.
Do you have any other concerns?

2022-10-18 10:12 UTC, posva requested changes
Can you remove the changes to the pnpm-lock? Rebasing should work. I think we can go ahead and merge this. We will migrate later on to the latest vitepress

2022-10-18 13:32 UTC, KimYangOfCat commented
pnpm-lock removed. thanks for merging! 
In the future, I am willing to help fix any problems with Chinese documentation.

2022-10-18 14:50 UTC, posva approved these changes
Thanks!

2022-10-18 14:50 UTC, merged

2022-10-18 17:07 UTC, arnonrdp commented
Amazing merge!
Does this mean that we now have open doors for other languages?
@KimYangOfCat, can we have some README.md with basic instructions for adding other languages?

2022-10-18 17:09 UTC, posva commented
Thanks for your interest! Other languages will be kept in other repositories, following the guide at https://github.com/vuejs-translations/guidelines/blob/main/README.md

2022-10-18 18:39 UTC, arnonrdp commented
Right, but they will be in the language dropdown of the main site (https://pinia.vuejs.org/) or it will be another url.

2022-10-18 18:55 UTC, posva commented
in the dropdown, pointing to an external site

2022-10-19 00:49 UTC, KimYangOfCat commented
Later, will the docs package be split into a new repository of the vuejs-translation org?

2022-10-19 01:55 UTC, awxiaoxian2020 commented
> Later, will the docs package be split into a new repository of the vuejs-translation org? Same as vue docs? maybe we should open a new issue to discuss this.

See also https://github.com/vuejs-translations/docs-zh-cn/discussions/561