fix: install plugins after app is set (#1063)
posva/pinia pull request #1392
Opened 2022-06-24 22:33 UTC by popov-a-e

Closes https://github.com/vuejs/pinia/issues/1063

Turned out in nuxt plugin environment, `pinia._a` is not yet defined which resulted in devtools unable to find app record.

2022-06-25 18:12 UTC, posva commented
Thanks for the PR but this completely changes the behavior of plugins. The fix should be possible with minimal changes and without changing how stores are initialized

2022-06-25 19:30 UTC, popov-a-e commented
Vue-devtools requires vue instance (app) for a plugin to be properly installed.
This instance might be uninitialized when useStore is called, there is no need for nuxt to reproduce that:
```
const pinia = createPinia()
useFooStore(pinia)
createApp(App).use(pinia)
```
So the only proper solution is to install (at least some) plugins only after app is created and installed to pinia.
I can do it via adding optional argument to `pinia.use` or create `pinia.useWithApp`, or extend `pinia.use` to allow adding plugins post-initialization.
Non of these seem beautiful to me, but I don't see better way without refactoring and with _minimal changes_, what do you think?

2022-06-25 19:54 UTC, popov-a-e commented
OK, I ended up applying same logic to devtools plugin only.
Tests checked.

2022-06-28 18:33 UTC, popov-a-e commented
@posva Hi Eduardo, is it OK now?

2022-10-06 14:00 UTC, posva requested changes
Thanks but we really want to avoid adding any new hook like this. 
Instead, let's move this kind of logic to the devtools: if the `registerPiniaDevtools()` haven't been called yet, we buffer the pending stores and once the devtools are registered, we add the store to the devtools.

2025-02-12 08:46 UTC, closed without merging