fix: injection "Symbol(pinia)" not found.
posva/pinia pull request #1849
Opened 2022-12-08 06:44 UTC by XRenSiu

issue #1650

2022-12-08 07:30 UTC, posva commented
This shouldn’t be necessary. Do you have a boiled down repro?

2022-12-08 16:42 UTC, XRenSiu commented
> This shouldn’t be necessary. Do you have a boiled down repro?

Reproduction: https://stackblitz.com/edit/vitejs-vite-t9sovg

2022-12-08 17:33 UTC, posva commented
Thanks!

The issue comes from the fact that `provide` doesn't work in the component passed to `new Vue()`, it does work in the one passed as `render: h => h(App)`. It counts as using the store globally, so passing the pinia instance will be necessary:

```ts
const app = new Vue({
  pinia,
  render: () => h(App),
  setup() {
    const store = useFooStore(pinia);
    const countStore = useCountStore(pinia);
    console.log(store.bar);
    console.log(countStore.count);
  },
});
```

However I think I have an idea to a simpler fix for this

2022-12-08 17:35 UTC, posva requested changes

2022-12-08 17:35 UTC, posva commented on packages/pinia/src/store.ts
> -      (currentInstance && inject(piniaSymbol))
Let's instead revert to the old version and give a default value to `inject(piniaSymbol, null)`. This should bypass the error and still work without false positives

2022-12-09 09:03 UTC, posva approved these changes

2022-12-09 10:23 UTC, merged