Docs/sheep
posva/pinia pull request #2094
Opened 2023-03-21 17:18 UTC by lion414

Translated some docs and modified some code

2023-04-03 09:23 UTC, posva commented
Can you rebase and see if there is anything left to add?

2023-04-04 04:29 UTC, lion414 commented
> Can you rebase and see if there is anything left to add?

So sorry, I have rebased this PR.

2023-04-04 13:13 UTC, posva commented
can you resolve the conflicts?

2023-04-04 19:07 UTC, lion414 commented
> can you resolve the conflicts?

The conflicts have been resolved.

2023-04-05 10:37 UTC, posva requested changes
Thanks!

2023-04-05 10:37 UTC, posva commented on packages/docs/cookbook/composing-stores.md
> +    return `Hi ${user.name}, you have ${list.value.length} items in your cart. It costs ${price.value}.`
we also need to add the `list` ref after `const user =...`

2023-04-05 10:37 UTC, posva commented on packages/docs/zh/cookbook/composing-stores.md
> +    return `Hi ${user.name}, you have ${list.value.length} items in your cart. It costs ${price.value}.`
same here

2023-04-05 13:38 UTC, posva approved these changes
Thanks! I will let @Jinjiang or any other native Chinese speaker review and merge!

2023-04-05 16:56 UTC, Jinjiang requested changes

2023-04-05 16:56 UTC, Jinjiang commented on packages/docs/zh/cookbook/composing-stores.md
> +    // ✅ 允许读取y中的属性在 computed 或 actions 中
```suggestion
    // ✅ 读取 computed 或 action 中的 y 属性
```

原译没有任何问题，甚至翻译得更好，建议保留，下同

2023-04-05 16:56 UTC, Jinjiang commented on packages/docs/zh/core-concepts/actions.md
> +// 此订阅器仍将保留，即使该组件被卸载
```suggestion
// 此订阅器即便在组件卸载之后仍会被保留
```

2023-04-05 16:56 UTC, Jinjiang commented on packages/docs/zh/core-concepts/index.md
> +// 同时通过插件添加的属性也会被提取为ref
```suggestion
// 同时通过插件添加的属性也会被提取为 ref
```

2023-04-05 16:56 UTC, Jinjiang commented on packages/docs/zh/core-concepts/index.md
> +// `name` 和 `doubleCount` 变成响应式ref
```suggestion
// `name` 和 `doubleCount` 是响应式的 ref
```

2023-04-05 16:56 UTC, Jinjiang commented on packages/docs/zh/core-concepts/index.md
> +// 并且会跳过所有的 action 或不是响应式(ref/reactive)的属性
```suggestion
// 并且会跳过所有的 action 或非响应式 (不是 ref 或 reactive) 的属性
```

2023-04-05 16:56 UTC, Jinjiang commented on packages/docs/zh/core-concepts/outside-component-usage.md
> +  // ✅ 这样做是可行的，因为路由器开始导航是在
```suggestion
  // ✅ 这样做是可行的，因为路由器是在其被安装之后开始导航的，
```

2023-04-05 16:56 UTC, Jinjiang commented on packages/docs/zh/core-concepts/outside-component-usage.md
> +  // 路由器被安装之后，而此时 Pinia 也已经被安装。
```suggestion
  // 而此时 Pinia 也已经被安装。
```

2023-04-05 16:56 UTC, Jinjiang commented on packages/docs/zh/core-concepts/plugins.md
> +如果你想给 store 添加新的 state 属性或者在水合(hydration)过程中使用的属性，**你必须同时在两个地方添加它**。
```suggestion
如果你想给 store 添加新的 state 属性或者在服务端渲染的激活过程中使用的属性，**你必须同时在两个地方添加它**。
```

2023-04-05 16:56 UTC, Jinjiang commented on packages/docs/zh/core-concepts/state.md
> +// 此订阅器仍将保留，即使该组件被卸载
```suggestion
// 此订阅器即便在组件卸载之后仍会被保留
```

2023-04-06 04:09 UTC, lion414 commented on packages/docs/zh/cookbook/composing-stores.md
> +    // ✅ 允许读取y中的属性在 computed 或 actions 中
原文：Read y properties in computed or actions
原文的意思是使用组合式stores时只有在 computed 或 actions 中才能去读取引入的别的 Store 中的属性比如例子中的y属性。
而现在的翻译 “读取 computed 或 action 中的 y 属性”是有歧义的，应该是“在computed 或 action 中读取y属性”。因为事实上在这个例子中computed和action 中并没有y属性。

2023-04-06 16:38 UTC, Jinjiang commented on packages/docs/zh/cookbook/composing-stores.md
> +    // ✅ 允许读取y中的属性在 computed 或 actions 中
Hi 基于整段文档的含义，你的理解是对的，但这里原文的注释并没有那么复杂的信息，我想说这里我们只做翻译，不做过度解读或推演，同时这也不代表原文有歧义。

如果你觉得这里的注释过于简单，那就不只是翻译的问题了，我个人并不介意继续深入讨论这个问题，但建议和这个翻译的 PR 分开，且针对内容本身的讨论最好用英文。

2023-04-08 09:24 UTC, Jinjiang approved these changes

2023-04-08 09:25 UTC, Jinjiang commented
@posva it looks all good now. Thanks.

2023-04-08 11:55 UTC, merged