Update index.md
posva/pinia pull request #2401
Opened 2023-09-07 01:54 UTC by ziyeyuecan

更新为语义更加明确的代码例子。
代码说明中缺少double，并且line119中出现了上文例子中并未定义的name，让读者有点不明所以。

2023-09-07 04:52 UTC, posva requested changes
Can you sync it to https://pinia.vuejs.org/core-concepts/?

2023-09-08 02:03 UTC, ziyeyuecan commented
我注意到上述语义不明确的问题只出现在中文文档中https://pinia.vuejs.org/zh/core-concepts/，英文文档https://pinia.vuejs.org/core-concepts/例子是准确无误的。

2024-01-09 00:48 UTC, awxiaoxian2020 commented
@posva It seems just Chinese Document typo. :)

2024-01-09 08:51 UTC, closed without merging

2024-01-09 08:52 UTC, posva commented
Thanks, I couldn't push to the PR so I fixed it locally