fix(docs): fix the Chinese api docs
posva/pinia pull request #2717
Opened 2024-07-15 08:54 UTC by zhangmo8

<img width="1164" alt="image" src="https://github.com/user-attachments/assets/cf74202e-8577-4ffe-b3cd-91f372117bd2">

2024-07-15 17:16 UTC, posva requested changes
Thanks! They files need to be updated instead of

2024-07-15 17:24 UTC, posva commented on packages/docs/zh/index.md
> +  text: "得心应手的 \nVue.js 状态管理库"
Let’s revert this to the original

2024-07-16 02:31 UTC, zhangmo8 commented on packages/docs/zh/index.md
> +  text: "得心应手的 \nVue.js 状态管理库"
Actually, I think it's better to be "得心应手"

2024-07-16 06:02 UTC, posva approved these changes

2024-07-16 06:03 UTC, merged