Migrate mockedStore typings to vitest v2
posva/pinia pull request #2759
Opened 2024-09-02 07:56 UTC by lud-hu

Migrate the typings of `mockedStore` to the changes of >vitest@2.0.0:

see:
https://vitest.dev/guide/migration#simplified-generic-types-of-mock-functions-e-g-vi-fn-t-mock-t
https://github.com/vitest-dev/vitest/releases/tag/v2.0.0

2024-09-02 11:09 UTC, posva approved these changes
Thanks!

2024-09-02 11:11 UTC, posva requested changes

2024-09-02 11:11 UTC, posva commented on packages/docs/cookbook/testing.md
> +            Mock<(args: Args) => ReturnT>
Although now it should be able to just take `Actions[K]`. I need to test it

2024-09-12 15:31 UTC, netroy commented on packages/docs/cookbook/testing.md
> +            Mock<(args: Args) => ReturnT>
Shouldn't this be

```suggestion
            Mock<(...args: Args) => ReturnT>
```

2024-10-09 09:43 UTC, closed without merging