fix: Error when _VUE_DEVTOOLS_TOAST_ is undefined
posva/pinia pull request #334
Opened 2021-01-15 15:57 UTC by timozander

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing
- [ ] New/updated tests are included

**Other information:**
When using Pinia v2 with the latest beta of Vue devtools, I always experience the following console error:

```
backend.js:3166 ReferenceError: __VUE_DEVTOOLS_TOAST__ is not defined
    at pinia.esm-bundler.js?v=94b0b286:232
    at Object.addPlugin (backend.js:3162)
    at Object.<anonymous> (backend.js:908)
    at Object.emit (<anonymous>:1:780)
    at Object._replayBuffer (<anonymous>:1:332)
    at Object.on (<anonymous>:1:424)
    at connect (backend.js:907)
```

While I cannot exactly pin down the exact cause of this, I think its reasonable to fall back to console output whenever the devtools's toast is not available

2021-01-16 18:19 UTC, posva commented
This is weird since the devtools should be installed at that point. I would need to have more details to ensure this is the right fix

2021-01-16 19:18 UTC, timozander commented
I found out that it is caused by the devtools failing to load a specific source (https://github.com/vuejs/vue-devtools/issues/1322#issuecomment-752352360)

However, I think that adding this extra sanity check is reasonable since relying on globally available methods like this is always at the risk of failure, causing console spam

2021-01-16 20:51 UTC, posva requested changes

2021-01-16 20:51 UTC, posva commented on src/devtools.ts
> +function outputMessage(
let's call it `toastMessage`

2021-01-16 20:51 UTC, posva commented on src/devtools.ts
> +  if (__VUE_DEVTOOLS_TOAST__) {
```suggestion
  if (typeof __VUE_DEVTOOLS_TOAST__ !== undefined) {
```

2021-01-16 20:51 UTC, posva commented on src/devtools.ts
> +    return
remove this return and use an `else`

2021-01-16 20:51 UTC, posva commented on src/devtools.ts
> +            outputMessage(`🍍 store "${payload.nodeId}" not found`, 'error')
let's move the `🍍 ` inside of the `toastMessage` in front of every message

2021-01-18 14:02 UTC, posva commented on src/devtools.ts
> +  const piniaMessage = '🍍' + message
```suggestion
  const piniaMessage = '🍍 ' + message
```

2021-01-18 14:03 UTC, posva commented on src/devtools.ts
> +  if (typeof __VUE_DEVTOOLS_TOAST__ !== 'undefined') {
```suggestion
  if (typeof __VUE_DEVTOOLS_TOAST__ === 'function') {
```

2021-01-18 14:04 UTC, posva approved these changes
Thanks!

2021-01-18 14:05 UTC, merged